### ISSUE TITLE
v9.0.3 Exception after answering Y on disabling Tired JIT Compilation

### ISSUE THREAD

**Issue by Quicksilv3r710** [cem3cem3/AppliedEcogisticsIssues#19]
After installing the mod and trying to boot up the server, I keep getting an error about the file being used by another process.  I've tried completely restarting the computer, and I've even freshly installed the server program onto another PC that has never had it installed before, and just installed only this mod, and get the same error.
[Dump.txt](https://github.com/cem3cem3/AppliedEcogisticsIssues/files/5313219/Dump.txt)

**Comment by cem3cem3** [comment]
That's odd. Are you launching multiple instances of the server?
Also if you know how to, check the resource monitor to see which process is keeping that file open. 

Regardless, you should be able to fix this issue if you go to the .net temporary folder for the server and modifying the EcoServer.runtimeconfig.json manually. It's the same path as in the exception message you provided.

Under "runtimeOptions", add the following: ` "configProperties": {"System.Runtime.TieredCompilation": "false"}`

In my case the contents of that file look like this:
`{
  "runtimeOptions": {
    "tfm": "netcoreapp3.1",
    "includedFrameworks": [
      {
        "name": "Microsoft.NETCore.App",
        "version": "3.1.4"
      },
      {
        "name": "Microsoft.AspNetCore.App",
        "version": "3.1.4"
      }
    ],
    "configProperties": {
      "System.Runtime.TieredCompilation": "false"
    }
  }
}`

**Comment by Quicksilv3r710** [comment]
After making that change to the ecoserver.runtimeconfig.json, I no longer get the "being used by another process" error, but now the server will boot up and get to the end, and just shutoff.  It's creating no log files, and I can't see any errors in the command prompt before it shuts off.  BTW, I'm not launching multiple instances of the server, and I can't see any processes keeping the file open. I had another person install the server program onto their computer (it has a fresh install of win 10) and make the same changes, and they get the same issues.  They also get the same issue about "being used by another process" before making the change to the file as well.

**Comment by cem3cem3** [comment]
The "being used by another process" should not cause the server to fail to start after you add the extra line to the runtimeconfig file.

If you're not getting logs, try making a batch script in the server directory and running it.
Call it something like "launch.bat" and add the two lines:
`EcoServer.exe`
`pause`

This should keep the console window open after it crashes.

**Comment by Quicksilv3r710** [comment]
Yes, the "being used by another process" goes away after adding that line of code, but the server will now get to "initializing world object manager" and just shutoff.  I am getting log files now, and here's the most recent one:
[log_201001040159.log](https://github.com/cem3cem3/AppliedEcogisticsIssues/files/5314536/log_201001040159.log)

**Comment by cem3cem3** [comment]
The latter issue you're having seems to be related to #20. I'll keep this issue open for the IO Error.

**Comment by cem3cem3** [comment]
Will print instructions on Disabling Tiered JIT Compilation now, instead of just crashing with an error.
