### ISSUE TITLE
v9.0.3 SIGSEGV when starting server on dedicated server

### ISSUE THREAD

**Issue by SirMishaa** [cem3cem3/AppliedEcogisticsIssues#20]
Hello, 

I installed your mods (applied_ecogistics_1_14_0_9_0_3r), I put the two files in the mods folder on the server, but towards the end of the loading, I have an error

Server is under Ubuntu 20.03, with .net core 3.1

![image](https://user-images.githubusercontent.com/42717232/94854230-e27f5580-042c-11eb-8e05-4befd004f2f5.png)

Segmentation fault 
I am at your disposal if you have more information.

I don't have a crash dump.
(I specify that this is the only mod I installed.)

**Comment by cem3cem3** [comment]
There should not be a SIGSEGV caused by my mod. I do not have any 'unsafe' code blocks that would let .net cause a memory access violation.

If you could, can you post the output of `dotnet --version`?

I have a similar setup with ubuntu 20.04 and dotnet core 3.1.101 and have not run into that error. If you are on 20.03, dotnet might have an incompatibility though.

**Comment by SirMishaa** [comment]
Here is a step-by-step description of what I did: 

- Download the mod
- Extracting the mod in the mod folder
- Launch the server

I had an error, "the mods compilation ended with an error".

Since then, it has been impossible to launch the server.

I'm under ``dotnet 3.1.402``

**Comment by SirMishaa** [comment]
![image](https://user-images.githubusercontent.com/42717232/94856820-d1d0de80-0430-11eb-8f57-d757f57e6a5b.png)

This is in the step "Initializing WorldObjectManager..."

**Comment by SirMishaa** [comment]
@cem3cem3 This is maybe an issue related to `` Tiered JIT Compilation`` ? 

Because I removed your mod, I even completely emptied the mods folder in order to put back the original and change an old backup and I still have the same problem.

**How can I reactivate Tiered JIT Compilation?**

**Comment by cem3cem3** [comment]
You can delete the directory: /var/tmp/.net/username/EcoServer.

Alternatively you can also find the EcoServer.runtimeconfig.json file in that directory and remove the line: `"System.Runtime.TieredCompilation": false`.

**Comment by SirMishaa** [comment]
Indeed, this is working when I remove the temp folder. 
I'll try again to install your mod and close this issue if it's working ! 

Thank you.

**Comment by SirMishaa** [comment]
![image](https://user-images.githubusercontent.com/42717232/94858776-dba81100-0433-11eb-978d-67ee7c41d05a.png)

Still the same issue. 

![image](https://user-images.githubusercontent.com/42717232/94858890-ff6b5700-0433-11eb-82cd-25be361186e6.png)
This seems to have an issue when compiling mods

**Comment by SirMishaa** [comment]
After deleting the cache, when starting the server, it asks me again to disable the Tiered JIT compilation.

Maybe it doesn't disable properly ? Should I disable it globally ?

![image](https://user-images.githubusercontent.com/42717232/94859284-933d2300-0434-11eb-81c3-1ea5cd724981.png)

**Comment by cem3cem3** [comment]
But it works fine without the mod?
The line "Mods recompiled with errors" is for compiling the .cs files in the mods folder. You'll notice it mentions "Loading ItemSystem..." after this line.
Try deleting the Mods folder and re-downloading it.

I wouldn't advise disabling Tiered JIT globally, as this actually would cause performance degradation for all .net applications.

**Comment by SirMishaa** [comment]
Yes, it works without the mod.

Can I give you my backup? Maybe the error will occur with my backup.

I have already replaced the mods folder with the original folder and deleted the cache but it doesn't work.

(~/test contains the original ECO 9.0.3 files)
![image](https://user-images.githubusercontent.com/42717232/94860859-ef08ab80-0436-11eb-8c66-0d34cd9a6c1f.png)

I still have the error SIGSEGV
[ECOLAND.zip](https://github.com/cem3cem3/AppliedEcogisticsIssues/files/5314615/ECOLAND.zip)

**Comment by cem3cem3** [comment]
Yes, I managed to reproduce this with your world file. Just to make sure, check if the server still fails with a new world.

**Comment by SirMishaa** [comment]
This is seems to work with a new world.
But for the people and even for us, you will understand that it is impossible to start from the beginning with a new world. 

Is it possible to find a solution in order to play while keeping our save? 
Thank you for your work

**Comment by cem3cem3** [comment]
Of course I understand that it's not an option for everyone to start anew. For now, you will have to keep playing without the mod unfortunately...

Thank you a lot for your save file! Since I can reproduce the issue now, I'll be trying to figure out what's causing it and fix it.

**Comment by SirMishaa** [comment]
Sorry to reopen the issue but I see that the tag "fixed" has been added.

So can we finally play with the active mod on an already existing game?

**Comment by SirMishaa** [comment]
Update : This is seems to running well on the dedicated server. 

Thank you a lot !
