### ISSUE TITLE
Server Crash on startup (SocketException/InvalidOperationException)

### ISSUE THREAD

**Issue by demodude4u** [cem3cem3/AppliedEcogisticsIssues#29]
I got a strange error that does not appear related to this mod, but it only happens when this mod is installed.  When I remove the mod, this issue goes away.

I am running mod version 1.23.0.9.2.4E, server version 0.9.2.4 beta release-156.

![01HZPmu9gN](https://user-images.githubusercontent.com/2279262/110578890-b088c280-8133-11eb-83cb-26726192b362.png)

**Comment by D-Kay6** [comment]
Seems to be the same problem as #28 .
Based on [this](https://github.com/cem3cem3/AppliedEcogisticsIssues/issues/28#issuecomment-791830376) message.

**Comment by cem3cem3** [comment]
Turns out this is a harmony issue. I have notified their devs, but I won't be able to fix this until it gets sorted on their side unfortunately.

**Comment by cem3cem3** [comment]
While not fully fixed, the new version of the mod now uses a modified version of monomod.common that fails gracefully, instead of causing this issue. However, this means that on windows, you are again required to modify the EcoServer.runtimeconfig.json file as was the case with previous versions.

**Comment by cem3cem3** [comment]
While I haven't had the time to thoroughly test it, as my windows vm is giving me issues, the new version of harmony seems to fix the issue with Kestrel crashing as well as allowing Tiered JIT Compilation to stay enabled.
