### ISSUE TITLE
Crash on startup

### ISSUE THREAD

**Issue by DatPlatypus** [cem3cem3/AppliedEcogisticsIssues#31]
When starting up a singleplayer save (new save or old save), server crashes with, "Exception has been thrown by the target of an invocation."
Savefile works fine without mod installed.

Running on Eco 9.3.1, AE 1.24.0.9.3.0e.

Log attached.
[log_210416083817.log](https://github.com/cem3cem3/AppliedEcogisticsIssues/files/6328523/log_210416083817.log)

**Comment by cem3cem3** [comment]
`Server is not running in 64 bit mode. Applied Ecogistics (ItemSystem) may not function correctly in this mode. Please run the 64 bit server if you are running into errors`
Either try running the EcoServer.exe (not EcoServer32.exe) directly, or rename EcoServer.exe to EcoServer32.exe and try again to see if that was the problem.

**Comment by DatPlatypus** [comment]
Yup, that was it. Thanks!
