### ISSUE TITLE
It crashes my server

### ISSUE THREAD

**Issue by TheRedReaperTaken** [cem3cem3/AppliedEcogisticsIssues#33]
[log_210427053018.log](https://github.com/cem3cem3/AppliedEcogisticsIssues/files/6385813/log_210427053018.log)

^^^^^^^^^
That is the log and I have a 64 bit pc

**Comment by cem3cem3** [comment]
This isnt an issue caused by my mod. You seem to have an issue with a mod that adds Ink, quill pens and wax seals.
